### PR TITLE
Add warning to README

### PR DESCRIPTION
**Pull request by linas**

### CODE REVIEW

**Comment by linas** [comment]
Huh. OK, so I guess I don't have write access here. Nevermind.

**Comment by chenesan** [comment]
@linas I'm Ok to transfer the repo to opencog organization. 
It seems more convenient for the work and less misleading for others. How do you think about it?

**Comment by linas** [comment]
hi  Yi Shan  well, opencog already has a fork; Andrew wasn't familiar with github and pull from this, and that caused some confusion but I think its all sorted out now.

**Comment by chenesan** [comment]
OK I see. Just want to know if you need the transfering. ;)

**Comment by linas** [comment]
Is  there is any particular point to "transfering"?  I'm not quite sure what that means; could the repo be renamed?

**Pull request merged**
